version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:16-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Build and test
          command: npm run build && npm test:prod
      - run:
          name: Report coverage to Coveralls
          command: npm run coveralls

workflows:
  build-and-test:
    jobs:
      - build-and-test
